### ISSUE TITLE
feat: ✨ Tester le workshop 101-AI-and-py et ajouter les logiciels manquants 

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-and-py#106]
Modifier le Dockerfile pour faire fonctionner le workshop [101-AI-and-py](https://github.com/devrel-workshop/101-AI-and-py).

**Actions identifiées :**

 - au lancement cela clone [ai-as-lib-workshop](https://github.com/devrel-workshop/ai-as-lib-workshop), il faudrait que cela clone aussi [101-AI-and-py](https://github.com/devrel-workshop/101-AI-and-py)
 - comment mutualiser le docker utilisé pour booter le workshop `ai-as-lib-workshop` et `101-ai-and-py` : qd on fait les deux ça va que le Dockerfile soit ici mais si on ne fait que le `101-ai-and-py` cela peut poser pb. Un projet à part qui gère les images ? Un projet à part avec la base commune et le spécifique dans chaque projet ? Autre ?

see https://github.com/devrel-workshop/cde-images/issues/14

**Comment by scraly** [comment]
Pour le git clone, dans le template coder du workspace j'ai vu cette instruction

```
module "git-clone" {
  source      = "registry.coder.com/modules/git-clone/coder"
  version     = "1.0.18"
  agent_id    = coder_agent.main.id
  url         = "https://github.com/devrel-workshop/ai-as-lib-workshop"
  branch_name = "main"
}
```

Du coup il faudrait dupliquer le bloc de code pour également initier le git clone lors de l'initialisation du workspace AI, non ?

**Comment by philippart-s** [comment]
oui ça c'est qd tout marchera 😅, on fera peut être ça pour Polytech par soucis de facilité mais à terme il faudra voir comment on fait car on ne donne pas toujours les deux workshops ensembles.

Après ce n'est pas très grave d'avoir du code qui ne sert pas mais ça peut porter à confusion
