### ISSUE TITLE
doc: 🖼️ Porter slides Google Slides vers Canva

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-and-py#82]
Parce que c'est plus joli :=)

**Comment by philippart-s** [comment]
oh tu sais si il n'y avait que moi on aurait fait SliDesk 😉

**Comment by scraly** [comment]
Ouuuuhhh c'est honteux ^^

(Mami sort de sa sieste, elle peut dire des bêtises 😆)
