### ISSUE TITLE
feat: ✨ Update OVHAI CLI to the last version

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-and-py#89]
A new version of the CLI ovhai is available, update the Gitpod image.

**Comment by philippart-s** [comment]
Last version is bugged, wait for the fix before updating the Gitpod image.

**Comment by MathieuBsqt** [comment]
Bugged version is `3.22.6`. 
In case you update it to this version, you can fix your CLI by running

```
sed -i 's/access_key/accessKey/g' ~/.config/ovhai/context.json
sed -i 's/secret_key/secretKey/g' ~/.config/ovhai/context.json
```
