### ISSUE TITLE
bug: 🐛 Le nouveau Notebook ne détecte plus les signes mais les objets YOLOV8

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-and-py#90]
Suite à la modification du Notebook les tests dans le notebook ne détectent plus les signes pierre / feuille / ciseaux mais les objets classiques de YOLOV8.

![image](https://github.com/devrel-workshop/101-AI-and-py/assets/26224751/4b4563ab-d52a-4aae-b3c3-e6ea429be6f3)
![image](https://github.com/devrel-workshop/101-AI-and-py/assets/26224751/4209dbce-42c0-475c-b2c9-ad9233a781cd)

**Comment by MathieuBsqt** [comment]
Exp:
- le modèle entraîné avec 5 epochs ne fonctionne pas sur les images que l'on teste sur le notebook
- Celui entraîné sur 10 epochs avec les mêmes paramètres fonctionnent lors de l'inférence sur une caméra
- Le modèle entraîné sur 10 epochs semble correctement prédire les résultats lors de l'inférence sur caméra, mais ne semble pas détecter les images mises dans le notebook.

**Comment by MathieuBsqt** [comment]
Obs: 
- Indeed, it seems that we are not using the trained model to predict the image anymore. That is why it results as a "person" object. When changing this model for the exported weights, we do get a "paper" prediction.
- However, the trained model on 5 epochs is much less accurate than the previous 5 epochs version. For 10 epochs, it works better. So it could be a great idea to keep it for AI Training & Deploy, but maybe it would be better to keep the previous version for AI Notebooks. The results & the study of the performance graphs woud be more interesting.
